### ISSUE TITLE
Artifact Weapons

### ISSUE THREAD

**Issue by Exscidium** [AstralTeam/Astral#17]
Paladin artifact weapons bugged - cannot upgrade, does not retain artifact power upon logging out.

**Comment by AstralTeam** [comment]
Please use the following format when reporting an issue:

**Description:**

**Current behaviour: (Tell us what happens.)**

**Expected behaviour: (Tell us what should happen instead.)**

**Steps to reproduce the problem:**

**Comment by AstralTeam** [comment]
Working fine.
